active_links:
  ["Link1_L", "Link2_L", "Link3_L", "Link4_L", "Link5_L", "Link6_L", "Link7_L",
   "Link1_R", "Link2_R", "Link3_R", "Link4_R", "Link5_R", "Link6_R", "Link7_R"]
default_pose:
  [1.57, -1.57, -1.57, -1.57, 0.0, 0.0, 0.0,
   -1.57, -1.57, 1.57, -1.57, 0.0, 0.0, 0.0]
geometry:
  marvin_collision:
    spheres:
  
        base_link:
        # - center: [0.3, -0.2, 0.3]
        #   radius: 0.15
        - center: [0.0, -0.0, 0.1]
          radius: 0.10
        - center: [0.0, -0.0, 0.0]
          radius: 0.12
        - center: [0.0, -0.0, -0.1]
          radius: 0.12
        - center: [0.0, -0.0, -0.2]
          radius: 0.12
        - center: [0.0, -0.0, -0.3]
          radius: 0.12

        # - center: [0.20368,  0.1839866, 0.10]
        #   radius: 0.05
        # - center: [0.28368,  0.1839866, 0.10]
        #   radius: 0.05
        # - center: [0.36368,  0.1839866, 0.10]
        #   radius: 0.05
        # - center: [0.20368,  0.1339866, 0.00]
        #   radius: 0.05
        # - center: [0.28368,  0.1339866, 0.00]
        #   radius: 0.05
        # - center: [0.36368,  0.1339866, 0.00]
        #   radius: 0.05


        # - center: [0, 0, -0.15]
        #   radius: 0.06
        # - center: [0, 0, -0.15]
        #   radius: 0.045
        # - center: [0, 0, -0.20]
        #   radius: 0.045
        # - center: [0, 0, -0.15]
        #   radius: 0.06
        # - center: [0, 0, -0.15]
        #   radius: 0.045
        # - center: [0, 0, -0.20]
        #   radius: 0.045
        # - center: [0, 0, -0.15]
        #   radius: 0.06
        # - center: [0, 0, -0.15]
        #   radius: 0.045
        # - center: [0, 0, -0.20]
        #   radius: 0.045
        # - center: [0, 0, -0.15]
        #   radius: 0.06
        # - center: [0, 0, -0.15]
        #   radius: 0.045
        # - center: [0, 0, -0.20]
        #   radius: 0.045
        # left_link4:
        #   - center: [0, 0, 0.0]
        #     radius: 0.06
       

        # left_link5:

        # - center: [0, 0, -0.00]
        #   radius: 0.05
        # - center: [0, 0, -0.15]
        #   radius: 0.06


        # left_link7:
        # - center: [0, 0, 0.08]
        #   radius: 0.05
        # - center: [0, 0, 0.16]
        #   radius: 0.001
        # Link3_R:
        # - center: [0, 0, 0.1]
        #   radius: 0.06
        Link4_L:
        - center: [0, 0, 0.0]
          radius: 0.07
        Link4_R:
        - center: [0, 0, 0.0]
          radius: 0.07

        Link5_L:
        - center: [0, 0, -0.06]
          radius: 0.05
        - center: [0, 0, -0.10]
          radius: 0.045
        - center: [0, 0, -0.15]
          radius: 0.04


        Link5_R:
        - center: [0, 0, -0.06]
          radius: 0.05
        - center: [0, 0, -0.10]
          radius: 0.045
        - center: [0, 0, -0.15]
          radius: 0.04



        Link7_R:
        - center: [0, 0.0, 0.00]
          radius: 0.05
        # - center: [0, -0.08, 0]
          # radius: 0.04
        - center: [0, -0.10, 0]
          radius: 0.06
        # - center: [0, -0.28, 0]
        #   radius: 0.03
        # - center: [0, -0.084, -0.045]
        #   radius: 0.02

          
        Link7_L:
        - center: [0, 0.0, 0.00]
          radius: 0.05
        # - center: [0, -0.08, 0]
        #   radius: 0.04
        - center: [0, -0.10, 0]
          radius: 0.06
        # - center: [0, -0.25, 0]
        #   radius: 0.03



