sam3:
  checkpoint_path: Sam3Docker/model/sam3.1_multiplex.pt
  score_threshold: 0.45
  dedup_iou_threshold: 0.55
  suppress_contained_masks: true
  containment_threshold: 0.85
  bbox_containment_threshold: 0.85
  # containment_min_area_ratio: 1.2
  # prompts: cuboid box,yellow figurine,yellow long tassel, black box
  prompts: yellow box,white box,blue box

flowpose:
  paths:
    py_runner_path: FlowPoseDocker/FlowPose/py_runners
    pretrained_flow_model_path: FlowPoseDocker/model/flowpose.pth
    pretrained_scale_model_path: FlowPoseDocker/model/scalenet.pth
    dino_repo_path: FlowPoseDocker/model/facebookresearch_dinov2_main
  # visualization:
  #   fx: 606.9654541015625
  #   fy: 606.133056640625
  #   cx: 323.8822937011719
  #   cy: 257.6228332519531
  #   axis_len: 0.035
  #   width: 640
  #   height: 480 

  visualization:
    fx: 603.353
    fy: 602.621
    cx: 325.38
    cy: 241.099
    axis_len: 0.035
    width: 640
    height: 480 

siglip:   
  model:
    path: SiglipDocker/model/siglip2-so400m-patch14-224
    checkpoint: SiglipDocker/model/graspanything/0630m6weight/model_siglip2_multiview_v2_best_loss.pt
    graph_info_file: SiglipDocker/model/graspanything/0630m6weight/graph_info_19.json
    multiview: false
    num_views: 3
    num_query_tokens: 8
    pooler_num_layers: 2
    pooler_num_heads: 8
    background_mask_ratio: 0
  inference:
    topk: 5
    image_size: 224
    pad_head_ratio: 0.25
  runtime:
    topic: /siglip/result
    frame_id: camera_rgb_link
    capture_timeout: 2.0
    log_every: 10

marvin:
  object_yaml_path: MarvinDocker/robotaction/data/0626/test_box.yaml
  task_yaml_path: MarvinDocker/robotaction/data/0626/task.yaml 
  status_json_path: MarvinDocker/robotaction/data/0626/gift_m8_ego_0623.json
  status_topic: /siglip2/result
  progress_topic: /control/task_percentage
  object_tf_topic: ""
  base_frame: base_link
  tf_keepalive_hz: 10.0

realsense:
  width: 640
  height: 480
  fps: 30
  cameras:
    front:
      camera_name: camera_head
      camera_namespace: camera_head
      serial_no: _243222070778
      rgb_camera.color_profile: 640x480x30
      depth_module.depth_profile: 640x480x30
    head:
      camera_name: camera_head
      camera_namespace: camera_head
      serial_no: _243222070778
      rgb_camera.color_profile: 640x480x30
      depth_module.depth_profile: 640x480x30
    left:
      camera_name: camera_left_wrist
      camera_namespace: camera_left_wrist
      serial_no: _427622271868
      rgb_camera.color_profile: 640x480x30
      depth_module.color_profile: 640x480x30
      depth_module.depth_profile: 640x480x30
    right:
      camera_name: camera_right_wrist
      camera_namespace: camera_right_wrist
      serial_no: _412622270871
      rgb_camera.color_profile: 640x480x30
      depth_module.color_profile: 640x480x30
      depth_module.depth_profile: 640x480x30

fresh_tf:
  min_interval_sec: 1.0
  settle_sec: 0.15
  perception_camera: front
work_area:
  x_max: 1.0
  x_min: 0.25
  y_max: 0.5
  y_min: -0.5
  z_min: 0.66
  z_max: 0.75  
rosbag:
  save_path: /home/yang/auto_app/ros2data
  record_mode: per_target
  # record_mode: complete_loop
  stop_timeout_sec: 10.0
  critical_topics:
    - /fusion_pose
    - /fusion/current_action
    - /control/task_percentage
    - /control/target_poseR
    - /control/target_poseL
    - /control/speed_scale
    - /control/eef_constraint
    - /control/gripperValueR
    - /control/gripperValueL
